### PR TITLE
[Translation] Update zh_CN.po

### PR DESCRIPTION
**Pull request by WhiredPlanck**
Update Chinese Simplified translation.

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
Found some typos and incorrect translated strings. Will fix soon.

**Comment by WhiredPlanck** [comment]
https://github.com/bbidulock/icewm/pull/460/commits/1e5c34d6c7ba768a246133926f0f34c89e104855

Done.

**Comment by bbidulock** [comment]
Could someone associated with the project please double-check the changes (for obvious reasons)?

**Comment by gijsbers** [comment]
Looks good to me. Maybe @jidanni can read the changes too?

**Comment by WhiredPlanck** [comment]
> Looks good to me. Maybe @jidanni can read the changes too?

If it looks good, I think there should be no format errors but may inaccurate translations. : )

**Comment by jidanni** [comment]
Well, I only use the English version of  icewm, so am too lazy to help with any Chinese versions.

**Comment by WhiredPlanck** [comment]
> Well, I only use the English version of icewm, so am too lazy to help with any Chinese versions.

OK, that's fine.

**Pull request merged**
