### PR TITLE
Sso mod 4

### PR DESCRIPTION
**Pull request by Code7R**

### CODE REVIEW

**Comment by gijsbers** [comment]
It doesn't compile if `#if __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__`.

```
-    if (sig == SIGCHLD) {
-        int s, rc;
-        do {
-            rc = waitpid(-1, &s, WNOHANG);
-        } while (rc > 0);
-    }
+    if (sig != SIGCHLD)
+        return;
+    int s, rc;
+    do {
+        rc = waitpid(-1, &s, WNOHANG);
+    } while (rc > 0);
```
That is a degradation. I prefer a positive condition (test for what you want to be true),
with no return statements, if possible.

If's and for's are written as if they are function calls.

**Comment by Code7R** [comment]
That should be fine now, I dropped the remains of bit-level hackery which affected the endian issue (the macro was wrong anyway).
Tested successfully in PowerPC virtual environment, the best viable architecture I could come up with  which represents the 32bit && BE combination.

Not sure yet about non-GCC toolchains. The pointer conversion for non-GCC should be OK but I was not able to compile icewm with OracleStudio compiler due to strange issues (that also affects the icewm-1-4-BRANCH).

**Comment by Code7R** [comment]
PS: there is still some room for optimization regarding the printf formatting with a size hint (so, the caller shall remember the maximum size it needed last time). This task can be postponed, IMHO not urgent.

**Comment by gijsbers** [comment]
WRDE_DOOFFS disappeared in setKeyboard.
Some if's and for's are still written as a function call.
Some assignment operators lack surrounding spaces.
The LOC for mstring nearly doubled in size!
Which might mean: twice the bugs and a higher maintenance burden?
Compilation times increased by 12%.
Several "!isEmpty" can be written as "nonempty".
Is there any measurable gains in execution speed or memory usage?
Lots of new preprocessor lines can better be removed.

In nextTimeoutWithFuzz you introduce:

    +        if (!iter->isRunning())
    +            continue;
    +

but this is a unwanted degradation as explained previously.
Same for getTimeout.
Same for runProgram.
Same for getPrivConfDir.

MStringArray changed heavily, but is this supported by tests?

There are new unexpanded tabs in yicon.cc.

The YSparseHashTable is totally alien to the yarray.h concepts
and only used by yicon.

For wmLook testing the macro LOOK is preferred.

**Comment by Code7R** [comment]
> Some if's and for's are still written as a function call.

What do you mean with "as a function call" again and why is this thing (whatever it is) wrong?

> Some assignment operators lack surrounding spaces.

Ok, but not touching existing code.

> The LOC for mstring nearly doubled in size!
> Which might mean: twice the bugs and a higher maintenance burden?

a) according to sloccount it's just 2/3 extra code, not 100% ("doubled").
b) it contains alternative variants for "standard C++11" rather than gnuc++11 (pointer conversion via union). If we drop support for non-GCC-like compilers then this code can be gone but I am not ready for that yet.
c) the old code didn't support move semantics whatsoever, now it does
d) it now does zero-termination on-the-fly. Therefore, you can pass const-refs and still call c_str() on them, before this was not possible. Although for many cases const flag wasn't really really making a difference, I prefer code where the mutability permission is clearly visible from the calling convention. Giving this up just to work around c_str()'s non-const declaration, or alternatively, cloning the string later for the same reason, is just nasty, IMHO.

> Compilation times increased by 12%.

Yes but is not a big deal. In real time, it makes a difference of about ONE second on a 2yo desktop CPU. Less than 9 seconds on the oldest system in regular use here ATM. The heavier part was already shifted into mstringex.h to have less impact.

> Is there any measurable gains in execution speed or memory usage?

I will send my earlier evaluation results later.

> Lots of new preprocessor lines can better be removed.

They serve a purpose (see above). And some might be moved from header to code file but then again it might make optimization steps for the compiler more complicated or impossible (i.e. I would like to have the implementation of length() and mstring(null_ref...) exposed in the header).

I tried moving most of them into .cc file, result: the binary became 0.5 percent smaller and the build times are 1-2 percents faster, so basically the same. That probably means: less inlining was possible to GCC, OTOH the difference is negligible.

If you want to have this change applied, let me know.

If you want to optimize for size even further, building with LTO is possible, then the build will take many times more than 5 seconds (i.e. due to final non-parallel optimization run in the linker). And the resulting binary will be about 4% smaller.

> In nextTimeoutWithFuzz you introduce:
> 
> ```
> +        if (!iter->isRunning())
> +            continue;
> +
> ```
> 
> but this is a unwanted degradation as explained previously.
> Same for getTimeout.
> Same for runProgram.
> Same for getPrivConfDir.

Degradation of what? I see that as an improvement of readability by reducing pointless indentation. Who likes large huge if-blocks where you sometimes even have to scroll down a lot to see what happens in the else case, and then... HAHA, gotcha, there is no else case?

> MStringArray changed heavily, but is this supported by tests?

Is testarray.cc enough? Additional tests seemed to be unnecessary since it's basically std::deque now plus a few trivial adapters to retain the old API. I need to remove some bits from those tests, because not compatible but OTOH that code is no longer used so why shall they be kept (just to appease "yarray concepts??" see my rant below).

> There are new unexpanded tabs in yicon.cc.

... in a comment! *facepalm*
 
> The YSparseHashTable is totally alien to the yarray.h concepts

If you want it to be somewhere else, that can be moved for sure.

That said, I am triggered by "concepts" mentioned here. Maybe we we should reconsider the yarray's right to exist. I don't see significant benefits from it, it's messy, not well documented, and reinvents the wheel (the STL structures). The description mentions that it's "easy" (easy for whom?) and "reduce overhead caused by templates"... not sure what that overhead is supposed to be, maybe compilation times, maybe code size. Looks like ideas from the last millennium, but nowadays "make -j$(nproc) icewm" completes in roughly five seconds, and compilers starting from 2005 (or so) are pretty good on avoiding code duplication (there are exceptional cases, of course, but icewm code isn't a such one).

Admittedly, the STL has still its own dark corners because its designers wanted to be more generic that it's often needed while sacrificing some memory efficiency (one of the reasons why I implemented a custom hash table).

> and only used by yicon.

... and same applies to YAssocArray located right there, only used by apppstatus! Also, I smell some design flaws in YAssocArray, my original vision included ditching YAssoc and YAssocArray altogether and replacing them with YSparseHashTable even for apppstatus.

**Comment by gijsbers** [comment]
> What do you mean with "as a function call" again and why is this thing (whatever it is) wrong?

In https://en.wikipedia.org/wiki/Indentation_style#K&R_style
and https://stroustrup.com/PPP-style.pdf
after every language keyword which alters the flow of control
we always first insert a space before the parenthesis.
Only with function calls we don't and neither with language macros
like sizeof and typeof. If code complies with that then
it is often easier to read and maintain. In the icewm code
these conventions are followed and new code should do so too.

> > The LOC for mstring nearly doubled in size!
> > Which might mean: twice the bugs and a higher maintenance burden?
> 
> a) according to sloccount it's just 2/3 extra code, not 100% ("doubled").

I used "cloc" as `cloc mstring*[ch]`: 400 vs. 706 lines = 76.5% is nearly.
In file size bytes it is an increase of 86%.

> b) it contains alternative variants for "standard C++11" rather than gnuc++11 (pointer conversion via union). If we drop support for non-GCC-like compilers then this code can be gone but I am not ready for that yet.

Just a C++11 compiler should suffice to compile it anywhere.

> c) the old code didn't support move semantics whatsoever, now it does

Is that going to make a user-noticable difference anywhere ever?

> d) it now does zero-termination on-the-fly.
> 
> > Compilation times increased by 12%.
> 
> Yes but is not a big deal.

I do think it is valuable to have short edit-compile cycles.
Just increasing it for no good reason makes no sense then.

> > Lots of new preprocessor lines can better be removed.

To me all those lines make it still harder to read and test.

Every unique compile time conditional doubles the number of executables to test.

I think the developer needs to make a wise choice and not defer this to others.

> If you want to optimize for size even further, building with LTO is possible.

I couldn't get LTO to work on the BSDs or Solaris.
It also seems to take a long time to complete.
So I don't use it myself, because I want to recompile quickly.

> > but this is a unwanted degradation as explained previously.
> 
> Degradation of what?

Degradation of code quality, readability and maintainability.

> reducing pointless indentation.

No, all those returns and breaks and continues are like gotos.
They don't compute anything, but do add lines.
They redirect to some location which might be far away.
By keeping one complete flow from beginning to end, the true
structure of the function is reflected in the indentation.
If you feel the indentation nesting is too deep then the
complexity is probably too high anyway and you need to rethink
what you are doing and/or make smaller functions.

I also don't understand why these should go with a SSO project.

> Who likes large huge if-blocks ...

Ill-designed code isn't cured by inserting some gotos.

> > MStringArray changed heavily, but is this supported by tests?
> 
> Is testarray.cc enough?

MStringArray has 5 different uses and all need to remain bug free.

> > There are new unexpanded tabs in yicon.cc.
> 
> ... in a comment! *facepalm*

Doesn't the bottom line expand tabs for you?
// vim: set sw=4 ts=4 et:

>  
> > The YSparseHashTable is totally alien to the yarray.h concepts
> 
> If you want it to be somewhere else, that can be moved for sure.

ycollections.h isn't an improvement since we don't use that in icewm proper.

> Maybe we we should reconsider the yarray's right to exist.

No, it is well-proven stable code used everywhere, so we keep it as is.

>  ditching YAssoc and YAssocArray altogether.

YAssocArray has an interface which is consistent with other yarray.h
classes and that is valuable.  It is also much smaller and less complex
and hence easier to maintain for many years to come.

Consider this: only 8 out of 235 themes use non-default color specifications.
Yet the new use of precompiled_regex precompiles new regexes for every
startup of icewm, icewmbg and icehelp. That memory is not freed until exit.

So the code always takes time and allocates resources even though it is hardly ever needed.
From a code-style readability point of view the old code had a more declarative style
where the usage coincides with the definition. This is clearly superior.
The new situation requires more micro-management and the introduction
of new identifier names which previously where unneeded.

This is another example of optimization with no benefits, but which does
come with an increased maintenance burden. Hence the old situation was superior.
We should take the mantra "premature optimization is the root of all evil"
more seriously. This quote was by Tony Hoare and popularized by Donald Knuth.

If you do want to concentrate on optimization then I could give you some areas
which could make a user-noticable difference.

**Pull request closed without merging**
