### PR TITLE
Best way to create IceWM menu with icons

### PR DESCRIPTION
**Pull request by bedna-KU**
I tested MenuMaker - all is OK, but no icon at programs. Exist better script for create menu?

Thanks.

### CODE REVIEW

**Comment by Code7R** [comment]
Uhm, really? "bedna-KU wants to merge 173 commits"

I think you want to rebase it against Brian's current icewm-1-3-BRANCH .

**Comment by bedna-KU** [comment]
Sorry fail

**Comment by bbidulock** [comment]
I have two XDG compliant root menu generators that will generate menus complete with icons for icewm (and other popular light-weight window managers).  They will even put a menu in the system tray for you and can pop up the menu on a keystroke.  The first, written in "perl", is [xdg-traymenu](/bbidulock/xdg-traymenu).  The second, rewritten in "C", is [xde-menu](/bbidulock/xde-menu).  Coupled with the [xdg-launch](/bbidulock/xdg-launch) XDG compliant startup notification launcher, you have a fully compliant menu.

**Comment by bedna-KU** [comment]
Thank you very much.

**Pull request closed without merging**
