### PR TITLE
Finalized the addition of the 'Hibernate' option (to #737)

### PR DESCRIPTION
**Pull request by jinn-alt**
Pull request #737 is not were finalized. Icons were forgotten to add, hibernate command were added incorrectly in src/default.h file, the description of this option was also incorrectly in man/icewm-preferences.pod file. My pull request corrects this.

### CODE REVIEW

**Comment by gijsbers** [comment]
I fail to see a justification for the ` || :`. Can you remove it?

**Comment by jinn-alt** [comment]
`|| :` command is needed for that the command would not give an error, if all of the above commands are not present in the system. It is in the original man-page. If it disturb you, then I can remove it.

**Comment by gijsbers** [comment]
But without, if the commands are not found, is a non-zero exit code reported somehow? This doesn't seem so.
Actually, if a command fails to execute, this should be reported to the user. Otherwise he is waiting in vain for a command to execute. But you don't need to write that. If the `|| :` has no really useful function, then it should be removed. That is all.

**Comment by jinn-alt** [comment]
Well, fine. You have convinced me. Then so.

**Comment by gijsbers** [comment]
Are the icons installed as well? To that effect the icons must be added to lib/Makefile.am.

**Comment by jinn-alt** [comment]
Oh, sorry. I forgot about it. I build icewm package by CMake.
Then that the variant.

**Pull request merged**
