### PR TITLE
Extended strong control of startup sequence in icewm-session

### PR DESCRIPTION
**Pull request by jinn-alt**
On my netbook with Intel Atom CedarTrail inside zombie-window continues to appear with
probability about 90%.
I fixed it so: https://github.com/jinn-alt/icewm/commits/session_hack?page=3 , commits
https://github.com/bbidulock/icewm/commit/a7d3ed5d618e6f19a87d37070473d99934809376
https://github.com/bbidulock/icewm/commit/321aaff57e0ab8ee5a320b357f4752cbad44db50
Now the probability of occurence almost of zero.

### CODE REVIEW

**Comment by Code7R** [comment]
IMHO: looks sensible and good except for the annonated issues. Please change or explain, thanks.

**Comment by bbidulock** [comment]
I'm a little confused by these patches.  It appears that you have made all children execute sequentially using SIGUSR1 notification, instead of just assuring that the tray is up before the startup script is run; but how does this address zombies?  The only reaping problem that I see with the code is that WNOHANG should be removed (replaced with 0) in the waitpid statement to avoid races (a SIGCHLD was already received so a child is terminating even if its system state has not yet changed) and the 'while' changed to an 'if'.  Or, at least a wait without WNOHANG first and a do {} while with WNOHANG.

If you have startup processes that require the presence of a window manager or system tray, the typical approach with other light-weight window managers is to put 'sleep 2' at the beginning of the script.  (I was adjusting [xtoolwait](/XDesk/xtoolwait) to perform these tasks; but I suppose what is really needed is an 'xwmait', 'xtraywait' and 'xpagerwait' that behaves similar.)  What is creating the zombies?  Is it that programs in the startup script are running too soon?

**Comment by jinn-alt** [comment]
Yes exactly. I use SIGUSR1 to run and control the sequence of execution of children,
to make sure that by the time of execution of the Startup script tray is ready.
I actually used a script from which you run the program, setting down in the tray.
And zombie-window appears when the moment of launch tray is not ready. And I wanted
to get rid of "sleep" in the script. It turned out something like this.

**Comment by bbidulock** [comment]
I added xde-wait program to [xde-session](/bbidulock/xde-session) package that will wait for a tray to appear before executing a command.  That will get rid of your sleep.

**Pull request closed without merging**
